### ISSUE TITLE
Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead

### ISSUE THREAD

**Issue by BaseMax** [google/sentencepiece#740]
### pip install sentencepiece

```
Collecting sentencepiece
  Downloading sentencepiece-0.1.96.tar.gz (508 kB)
     ---------------------------------------- 508.6/508.6 KB 679.0 kB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: sentencepiece
  Building wheel for sentencepiece (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      C:\Python310\lib\site-packages\setuptools\dist.py:717: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
        warnings.warn(
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-3.10
      creating build\lib.win-amd64-3.10\sentencepiece
      copying src\sentencepiece/__init__.py -> build\lib.win-amd64-3.10\sentencepiece
      copying src\sentencepiece/sentencepiece_model_pb2.py -> build\lib.win-amd64-3.10\sentencepiece
      copying src\sentencepiece/sentencepiece_pb2.py -> build\lib.win-amd64-3.10\sentencepiece
      running build_ext
      building 'sentencepiece._sentencepiece' extension
      creating build\temp.win-amd64-3.10
      creating build\temp.win-amd64-3.10\Release
      creating build\temp.win-amd64-3.10\Release\src
      creating build\temp.win-amd64-3.10\Release\src\sentencepiece
      C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Python310\include -IC:\Python310\Include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt /EHsc /Tpsrc/sentencepiece/sentencepiece_wrap.cxx /Fobuild\temp.win-amd64-3.10\Release\src/sentencepiece/sentencepiece_wrap.obj /MT /I..\build\root\include
      cl : Command line warning D9025 : overriding '/MD' with '/MT'
      sentencepiece_wrap.cxx
      src/sentencepiece/sentencepiece_wrap.cxx(2809): fatal error C1083: Cannot open include file: 'sentencepiece_processor.h': No such file or directory
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for sentencepiece
  Running setup.py clean for sentencepiece
Failed to build sentencepiece
Installing collected packages: sentencepiece
  Running setup.py install for sentencepiece ... error
  error: subprocess-exited-with-error

  × Running setup.py install for sentencepiece did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      C:\Python310\lib\site-packages\setuptools\dist.py:717: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
        warnings.warn(
      running install
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-3.10
      creating build\lib.win-amd64-3.10\sentencepiece
      copying src\sentencepiece/__init__.py -> build\lib.win-amd64-3.10\sentencepiece
      copying src\sentencepiece/sentencepiece_model_pb2.py -> build\lib.win-amd64-3.10\sentencepiece
      copying src\sentencepiece/sentencepiece_pb2.py -> build\lib.win-amd64-3.10\sentencepiece
      running build_ext
      building 'sentencepiece._sentencepiece' extension
      creating build\temp.win-amd64-3.10
      creating build\temp.win-amd64-3.10\Release
      creating build\temp.win-amd64-3.10\Release\src
      creating build\temp.win-amd64-3.10\Release\src\sentencepiece
      C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Python310\include -IC:\Python310\Include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt /EHsc /Tpsrc/sentencepiece/sentencepiece_wrap.cxx /Fobuild\temp.win-amd64-3.10\Release\src/sentencepiece/sentencepiece_wrap.obj /MT /I..\build\root\include
      cl : Command line warning D9025 : overriding '/MD' with '/MT'
      sentencepiece_wrap.cxx
      src/sentencepiece/sentencepiece_wrap.cxx(2809): fatal error C1083: Cannot open include file: 'sentencepiece_processor.h': No such file or directory
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> sentencepiece

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```

It seems the problem not related to this project. but anyway I am reposting...

Best

**Comment by BaseMax** [comment]
Does windows supported for this lib?

**Comment by taku910** [comment]
Fixed. You can download the python3.10 whl package via pip.

**Comment by BaseMax** [comment]
Thanks, works.
```
C:\Users\MAX>pip install sentencepiece
Collecting sentencepiece
  Downloading sentencepiece-0.1.96-cp310-cp310-win_amd64.whl (1.1 MB)
     ---------------------------------------- 1.1/1.1 MB 433.9 kB/s eta 0:00:00
Installing collected packages: sentencepiece
Successfully installed sentencepiece-0.1.96

C:\Users\MAX>
```

**Comment by Sumasrikanth** [comment]
While iam working with charm-crypto==0.50
when i install pip install sovrin 

Collecting sovrin
  Using cached sovrin-1.1.23.tar.gz (8.2 kB)
  Preparing metadata (setup.py) ... done
  Using cached sovrin-1.1.22.tar.gz (8.2 kB)
  Preparing metadata (setup.py) ... done
  Using cached sovrin-1.1.21.tar.gz (8.2 kB)
  Preparing metadata (setup.py) ... done
  Using cached sovrin-1.1.20.tar.gz (8.2 kB)
  Preparing metadata (setup.py) ... done
  Using cached sovrin-1.1.19.tar.gz (8.2 kB)
  Preparing metadata (setup.py) ... done
  Using cached sovrin-1.1.18.tar.gz (8.2 kB)
  Preparing metadata (setup.py) ... done
  Using cached sovrin-1.1.17.tar.gz (8.1 kB)
  Preparing metadata (setup.py) ... done
Collecting indy-plenum==1.6.51 (from indy-node==1.6.73->sovrin)
  Using cached indy-plenum-1.6.51.tar.gz (725 kB)
  Preparing metadata (setup.py) ... done
Collecting indy-anoncreds==1.0.11 (from indy-node==1.6.73->sovrin)
  Using cached indy-anoncreds-1.0.11.tar.gz (37 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: python-dateutil in /home/sumalatha/.local/lib/python3.8/site-packages (from indy-node==1.6.73->sovrin) (2.8.2)
Collecting timeout-decorator==0.4.0 (from indy-node==1.6.73->sovrin)
  Using cached timeout-decorator-0.4.0.tar.gz (4.7 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: Charm-Crypto in /usr/local/lib/python3.8/dist-packages/Charm_Crypto-0.50-py3.8-linux-x86_64.egg (from indy-anoncreds==1.0.11->indy-node==1.6.73->sovrin) (0.50)
Collecting lazy-object-proxy (from indy-anoncreds==1.0.11->indy-node==1.6.73->sovrin)
  Using cached lazy_object_proxy-1.10.0-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.8 kB)
Requirement already satisfied: base58 in /usr/local/lib/python3.8/dist-packages (from indy-anoncreds==1.0.11->indy-node==1.6.73->sovrin) (2.1.1)
Collecting jsonpickle==0.9.6 (from indy-plenum==1.6.51->indy-node==1.6.73->sovrin)
  Using cached jsonpickle-0.9.6.tar.gz (67 kB)
  Preparing metadata (setup.py) ... done
Collecting ujson==1.33 (from indy-plenum==1.6.51->indy-node==1.6.73->sovrin)
  Using cached ujson-1.33.zip (197 kB)
  Preparing metadata (setup.py) ... done
Collecting prompt_toolkit==0.57 (from indy-plenum==1.6.51->indy-node==1.6.73->sovrin)
  Using cached prompt_toolkit-0.57-py3-none-any.whl.metadata (6.3 kB)
Collecting pygments==2.2.0 (from indy-plenum==1.6.51->indy-node==1.6.73->sovrin)
  Using cached Pygments-2.2.0-py2.py3-none-any.whl.metadata (1.5 kB)
Collecting rlp==0.5.1 (from indy-plenum==1.6.51->indy-node==1.6.73->sovrin)
  Using cached rlp-0.5.1-py2.py3-none-any.whl.metadata (1.3 kB)
Collecting sha3==0.2.1 (from indy-plenum==1.6.51->indy-node==1.6.73->sovrin)
  Using cached sha3-0.2.1.tar.gz (616 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: leveldb in /usr/local/lib/python3.8/dist-packages (from indy-plenum==1.6.51->indy-node==1.6.73->sovrin) (0.201)
Collecting ioflo==1.5.4 (from indy-plenum==1.6.51->indy-node==1.6.73->sovrin)
  Using cached ioflo-1.5.4.tar.gz (228 kB)
  Preparing metadata (setup.py) ... done
Collecting semver==2.7.9 (from indy-plenum==1.6.51->indy-node==1.6.73->sovrin)
  Using cached semver-2.7.9.tar.gz (5.8 kB)
  Preparing metadata (setup.py) ... done
Collecting base58 (from indy-anoncreds==1.0.11->indy-node==1.6.73->sovrin)
  Using cached base58-1.0.0.tar.gz (3.0 kB)
  Preparing metadata (setup.py) ... done
Collecting orderedset==2.0 (from indy-plenum==1.6.51->indy-node==1.6.73->sovrin)
  Using cached orderedset-2.0.tar.gz (78 kB)
  Preparing metadata (setup.py) ... done
Collecting sortedcontainers==1.5.7 (from indy-plenum==1.6.51->indy-node==1.6.73->sovrin)
  Using cached sortedcontainers-1.5.7-py2.py3-none-any.whl.metadata (9.6 kB)
Collecting psutil==5.4.3 (from indy-plenum==1.6.51->indy-node==1.6.73->sovrin)
  Using cached psutil-5.4.3.tar.gz (412 kB)
  Preparing metadata (setup.py) ... done
Collecting pip<10.0.0 (from indy-plenum==1.6.51->indy-node==1.6.73->sovrin)
  Using cached pip-9.0.3-py2.py3-none-any.whl.metadata (2.6 kB)
Collecting portalocker==0.5.7 (from indy-plenum==1.6.51->indy-node==1.6.73->sovrin)
  Using cached portalocker-0.5.7.tar.gz (7.4 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [3 lines of output]
      /home/sumalatha/.local/lib/python3.8/site-packages/setuptools/dist.py:717: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
        warnings.warn(
      error in portalocker setup command: use_2to3 is invalid.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
please help me out....
