### ISSUE TITLE
Doesn't seem to work with Python 3.13

### ISSUE THREAD

**Issue by tprrt** [google/sentencepiece#1069]
The following issue occurs with Python 3.13, but no issues occur with Python 3.11:

```
>>> import sentencepiece as spm
Traceback (most recent call last):
  File '<stdin>', line 1, in <module>
    import sentencepiece as spm
  File '/usr/lib/python3.13/site-packages/sentencepiece/__init__.py', line 10, in <module>
    from . import _sentencepiece
ImportError: cannot import name '_sentencepiece' from partially initialized module 'sentencepiece' (most likely due to a circular import) (/usr/lib/python3.13/site-packages/sentencepiece/__init__.py)
>>> exit()
```

**Comment by Kreijstal** [comment]
rip sentencepiece

**Comment by severinsimmler** [comment]
@taku910 Are you planning to release wheels for Python 3.13 and can we support you somehow?

**Comment by hxx221** [comment]
not work in py3.13 when to fix this issue？thank you

**Comment by Kreijstal** [comment]
Okay, who is forking it, where is the repo, who is the new juicy mantainer? we have a repo... to mantain

**Comment by h-vetinari** [comment]
You can install sentencepiece (tested to pass the test suite) for python 3.9-3.13 from conda-forge:
```
conda install -c conda-forge sentencepiece
```
Or use the compatible [`mamba`](https://mamba.readthedocs.io/en/latest/index.html) installer or the next-gen [`pixi`](https://pixi.sh/latest/)

**Comment by arabyserv** [comment]
not work for python 3.13
please we need support

**Comment by dsnehitha** [comment]
i had issue installing sentencepiece on python 3.13.1 because of build wheels but _**conda-forge**_ worked for me

**Comment by Sdreamtale** [comment]
> You can install sentencepiece (tested to pass the test suite) for python 3.9-3.13 from conda-forge:
> 
> ```
> conda install -c conda-forge sentencepiece
> ```
> 
> (you can also use the compatible [`mamba`](https://mamba.readthedocs.io/en/latest/index.html) installer or the next-gen [`pixi`](https://pixi.sh/latest/) instead of `conda`)
I don't know where to run”conda install -c conda-forge sentencepiece”.

**Comment by h-vetinari** [comment]
> I don't know where to run ”conda install -c conda-forge sentencepiece”.

Well, you need to install the tool called `conda` first (for example from [here](https://github.com/conda-forge/miniforge/releases); or one of the equivalent tools that I mentioned, which also follow the same paradigm: `mamba` or `pixi`), then you can install packages from conda-forge. Here's a little [primer](https://mamba.readthedocs.io/en/latest/user_guide/mamba.html) on using mamba, for example

**Comment by ricperry** [comment]
Using conda isn't an option for PyTorch+ROCm. We need default python 3.13 compatibility without having to jump through so many hoops.

![Image](https://github.com/user-attachments/assets/035df189-a399-43bc-88a6-f9041e781fb2)

**Comment by h-vetinari** [comment]
> Using conda isn't an option for PyTorch+ROCm.

You can `pip install` things into a conda-environment (e.g. install pytorch+ROCM into an env which contains `sentencepiece`). For rocm support, we'd like to provide that, feel free to help push https://github.com/conda-forge/conda-forge.github.io/issues/1923 forward.

**Comment by tousif47** [comment]
In few months Python 3.14 will be released and here it doesn't even work on 3.13 yet.
